'use strict';
const $=id=>document.getElementById(id);
const CFG={down:'https://speed.cloudflare.com/__down?bytes=',up:'https://speed.cloudflare.com/__up',trace:'https://speed.cloudflare.com/cdn-cgi/trace'};
let mode='quick',running=false,last=null,points=[],history=[],settingsData={duration:6,units:'Mbps',motion:'auto'};
try{const h=JSON.parse(localStorage.getItem('dvilr-speed-history')||'[]');history=Array.isArray(h)?h:[];const s=JSON.parse(localStorage.getItem('dvilr-speed-settings')||'{}');if(s&&typeof s==='object')settingsData={...settingsData,...s}}catch(e){}
settingsData.duration=[4,6,10].includes(+settingsData.duration)?+settingsData.duration:6;
settingsData.units=['Mbps','Gbps'].includes(settingsData.units)?settingsData.units:'Mbps';
settingsData.motion=['auto','reduce','on'].includes(settingsData.motion)?settingsData.motion:(settingsData.motion==='off'?'on':'auto');
history=history.filter(x=>x&&Number.isFinite(+x.down)&&Number.isFinite(+x.up)).slice(-50);
const save=()=>{try{localStorage.setItem('dvilr-speed-history',JSON.stringify(history));localStorage.setItem('dvilr-speed-settings',JSON.stringify(settingsData))}catch(e){}};
function fmt(n){n=+n;if(!Number.isFinite(n))return '—';return settingsData.units==='Gbps'?(n/1000).toFixed(n>=1000?2:3):(n>=100?n.toFixed(0):n.toFixed(2))}
function toast(t){const e=$('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200)}
function modal(title,body){$('modalbody').replaceChildren();const h=document.createElement('h2');h.textContent=title;$('modalbody').append(h);$('modalbody').insertAdjacentHTML('beforeend',body);$('modal').classList.add('show')}
function closeModal(){$('modal').classList.remove('show')}
function applyMotion(){const root=document.documentElement;root.classList.toggle('reduced-motion',settingsData.motion==='reduce');root.classList.toggle('forced-motion',settingsData.motion==='on')}
function refreshUnits(){
 $('unit').textContent=settingsData.units+' '+(last?'FINAL':'READY');
 document.querySelectorAll('.metric small').forEach((el,i)=>{if(i<2)el.textContent=(i===0?'DOWNLOAD ':'UPLOAD ')+settingsData.units});
 if(last)render(last); else renderHistory();
}
function settings(){
 modal('⚙ DVILR SPEED Settings','<div class="settings"><label>Test duration<select id="setDuration"><option value="4">4 seconds</option><option value="6">6 seconds</option><option value="10">10 seconds</option></select></label><label>Speed units<select id="setUnits"><option value="Mbps">Mbps</option><option value="Gbps">Gbps</option></select></label><label>Motion<select id="setMotion"><option value="auto">Follow device</option><option value="reduce">Reduce motion</option><option value="on">Animations on</option></select></label><button class="tool" id="clearHistory" type="button">🗑 Clear local history</button><div class="hint" id="settingsStatus">Settings are saved automatically.</div></div>');
 const d=$('setDuration'),u=$('setUnits'),m=$('setMotion');
 d.value=String(settingsData.duration);u.value=settingsData.units;m.value=settingsData.motion;
 d.addEventListener('change',()=>{settingsData.duration=+d.value;save();$('settingsStatus').textContent='✓ Test duration: '+settingsData.duration+' seconds. Next test will use it.';toast('Duration saved')});
 u.addEventListener('change',()=>{settingsData.units=u.value;save();refreshUnits();$('settingsStatus').textContent='✓ Speed units: '+settingsData.units+'. Display updated now.';toast('Units changed to '+settingsData.units)});
 m.addEventListener('change',()=>{settingsData.motion=m.value;save();applyMotion();$('settingsStatus').textContent=m.value==='reduce'?'✓ Reduced motion enabled.':m.value==='on'?'✓ Animations enabled.':'✓ Following your device motion preference.';toast('Motion setting saved')});
 $('clearHistory').addEventListener('click',()=>{history=[];last=null;save();renderHistory();$('speed').textContent='0';$('unit').textContent=settingsData.units+' READY';$('phase').textContent='Ready — choose a test mode';toast('Local history cleared')});
}
function request(url,opt={},ms=12000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);return fetch(url,{...opt,signal:c.signal,cache:'no-store',credentials:'omit',redirect:'error'}).finally(()=>clearTimeout(t))}
async function probe(){const t=performance.now();const r=await request(CFG.down+'1000&r='+Math.random(),{},8000);if(!r.ok)throw Error();return performance.now()-t}
async function latency(){const a=[];for(let i=0;i<5;i++){try{a.push(await probe())}catch(e){}if(i<4)await new Promise(r=>setTimeout(r,60))}if(!a.length)return{ping:999,jitter:999,loss:100};const p=a.reduce((a,b)=>a+b,0)/a.length,j=Math.sqrt(a.reduce((s,v)=>s+(v-p)**2,0)/a.length);return{ping:p,jitter:j,loss:(1-a.length/5)*100}}
async function download(sec){const start=performance.now(),end=start+sec*1000;let bytes=0,lastT=start,lastB=0;points=[];while(performance.now()<end){try{const r=await request(CFG.down+'10000000&r='+Math.random(),{},14000);if(!r.body)break;const rd=r.body.getReader();while(performance.now()<end){const q=await rd.read();if(q.done)break;bytes+=q.value.byteLength;const now=performance.now();if(now-lastT>=120){live((bytes-lastB)*8/(now-lastT)/1000,(now-start)/(sec*1000));lastT=now;lastB=bytes}}try{await rd.cancel()}catch(e){}}catch(e){}}return bytes*8/Math.max(100,performance.now()-start)}
async function upload(sec){const start=performance.now(),end=start+sec*1000,buf=new Uint8Array(512*1024);let bytes=0;while(performance.now()<end){try{await request(CFG.up+'?r='+Math.random(),{method:'POST',body:buf,headers:{'Content-Type':'application/octet-stream','Cache-Control':'no-cache'}},14000);bytes+=buf.byteLength;const now=performance.now();live(bytes*8/Math.max(100,now-start)/1000,(now-start)/(sec*1000))}catch(e){break}}return bytes*8/Math.max(100,performance.now()-start)}
function live(v,p){$('speed').textContent=fmt(v);$('unit').textContent=settingsData.units+' LIVE';$('bar').style.width=Math.min(100,Math.max(0,p*100))+'%';points.push(v);if(points.length>100)points.shift();draw()}
function draw(){const c=$('graph');if(!c)return;const r=c.getBoundingClientRect();if(!r.width||!r.height)return;const d=devicePixelRatio||1;c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);const w=r.width,h=r.height;x.clearRect(0,0,w,h);x.strokeStyle='#192338';for(let y=20;y<h;y+=25){x.beginPath();x.moveTo(0,y);x.lineTo(w,y);x.stroke()}if(points.length<2)return;const m=Math.max(10,...points),step=w/(points.length-1);x.beginPath();points.forEach((v,i)=>{const px=i*step,py=h-8-v/m*(h-18);i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle='#29d9ff';x.lineWidth=2;x.stroke()}
function health(r){return Math.round(Math.min(100,r.down/5)*.22+Math.min(100,r.up/2)*.15+Math.max(0,100-r.ping)*.22+Math.max(0,100-r.jitter*4)*.12+Math.max(0,100-r.loss*20)*.12+Math.max(0,100-r.jitter*2-r.loss*15)*.17)}
function render(r){last=r;[['down',fmt(r.down)],['up',fmt(r.up)],['ping',r.ping.toFixed(1)],['jitter',r.jitter.toFixed(1)]].forEach(a=>$(a[0]).textContent=a[1]);const s=health(r);$('score').textContent=s;$('scorebar').style.width=s+'%';$('rating').textContent=s>=90?'Excellent':s>=75?'Great':s>=55?'Good':s>=35?'Fair':'Poor';[['sd',Math.min(100,r.down/5)],['su',Math.min(100,r.up/2)],['sp',Math.max(0,100-r.ping)],['sj',Math.max(0,100-r.jitter*4)],['sl',Math.max(0,100-r.loss*20)],['ss',Math.max(0,100-r.jitter*2-r.loss*15)]].forEach(a=>$(a[0]).textContent=Math.round(a[1]));$('loss').textContent=r.loss.toFixed(1)+'%';$('loaded').textContent=r.ping.toFixed(0)+' ms';$('stability2').textContent=Math.round(Math.max(0,100-r.loss*20-r.jitter*2))+'%';const game=r.ping<35&&r.jitter<8&&r.loss<1?'Excellent':r.ping<60&&r.jitter<15&&r.loss<2?'Good':r.ping<100?'Playable':'Poor';['fortnite','valorant','cod'].forEach(id=>$(id).textContent=game);$('cloud').textContent=r.ping<40&&r.jitter<10?'Excellent':r.ping<70?'Good':'Limited';$('s1080').textContent=r.down>=5?'Ready':'Limited';$('s1440').textContent=r.down>=10?'Ready':'Limited';$('s4k').textContent=r.down>=25?'Ready':'Limited';$('calls').textContent=r.down>=15&&r.up>=5&&r.ping<80?'Excellent':r.down>=5&&r.up>=2?'Good':'Limited';$('unit').textContent=settingsData.units+' FINAL';renderHistory()}
function renderHistory(){const h=$('history');h.replaceChildren();if(!history.length){const e=document.createElement('div');e.className='empty';e.textContent='No tests saved on this device yet.';h.append(e);$('best').textContent=$('avg').textContent=$('trend').textContent='—';return}history.slice().reverse().forEach(v=>{const row=document.createElement('div');row.className='hist';[new Date(v.ts).toLocaleString(),fmt(v.down),fmt(v.up),Number(v.ping).toFixed(0),Number(v.jitter).toFixed(0)].forEach(t=>{const s=document.createElement('span');s.textContent=t;row.append(s)});h.append(row)});const ds=history.map(v=>+v.down);$('best').textContent=fmt(Math.max(...ds))+' '+settingsData.units;$('avg').textContent=fmt(ds.reduce((a,b)=>a+b,0)/ds.length)+' '+settingsData.units;$('trend').textContent=ds.length>1?(ds.at(-1)>=ds.at(-2)?'↗ Improving':'↘ Lower'):'—'}
async function trace(){const t=performance.now();try{const r=await request(CFG.trace,{},8000),text=await r.text(),m={};text.split(/\r?\n/).forEach(x=>{const p=x.indexOf('=');if(p>0)m[x.slice(0,p)]=x.slice(p+1)});$('edge').textContent=m.colo||'Cloud edge';$('location').textContent=m.loc||'Detected';$('edgeping').textContent=(performance.now()-t).toFixed(0)+' ms';$('edgehealth').textContent='● Healthy';$('dns').textContent=(performance.now()-t).toFixed(0)+' ms'}catch(e){$('edge').textContent='Unavailable';$('location').textContent='Browser-only';$('edgehealth').textContent='● Unverified';$('dns').textContent='Unavailable'}}
async function run(){if(running)return;if(!navigator.onLine){toast('Offline — connect to the internet first');return}running=true;$('start').disabled=true;$('orb').classList.add('run');$('phase').textContent='Measuring latency…';$('bar').style.width='0%';try{const l=await latency();$('ping').textContent=l.ping.toFixed(1);$('jitter').textContent=l.jitter.toFixed(1);$('phase').textContent='Measuring download…';const d=await download(+settingsData.duration||6);if(d<=0)throw Error('download');$('phase').textContent='Measuring upload…';const u=await upload(Math.max(2,Math.round((+settingsData.duration||6)*.65)));if(u<=0)throw Error('upload');const r={down:d,up:u,ping:l.ping,jitter:l.jitter,loss:l.loss,ts:Date.now()};render(r);history.push(r);history=history.slice(-50);save();$('speed').textContent=fmt(r.down);$('unit').textContent=settingsData.units+' FINAL';$('bar').style.width='100%';$('phase').textContent='Complete — result saved locally';toast('Test complete');await trace()}catch(e){$('phase').textContent='Test failed — endpoint or network unavailable';toast('Test could not complete')}finally{running=false;$('start').disabled=false;$('orb').classList.remove('run')}}
function share(){if(!last){toast('Run a test first');return}const text=`DVILR SPEED X — ${fmt(last.down)} ${settingsData.units} download, ${fmt(last.up)} ${settingsData.units} upload, ${last.ping.toFixed(0)} ms ping, health ${health(last)}/100.`;modal('📤 Share Result',`<div class="sharecard"><div class="big">${fmt(last.down)} ${settingsData.units}</div><div>${fmt(last.up)} ${settingsData.units} upload · ${last.ping.toFixed(0)} ms ping</div><p>Health ${health(last)}/100</p></div><div class="tools"><button class="tool" id="copy" type="button">📋 Copy result</button><button class="tool" id="native" type="button">📤 Share</button></div>`);$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(text);toast('Copied');closeModal()}catch(e){toast('Clipboard unavailable')}};$('native').onclick=async()=>{if(!navigator.share){toast('Sharing unavailable');return}try{await navigator.share({title:'DVILR SPEED X Result',text})}catch(e){}}}
function servers(){modal('🔀 Server & Endpoint','<p class="hint">DVILR SPEED X uses a fixed browser-safe HTTPS measurement service. It does not accept arbitrary URLs.</p><div class="result"><b>Cloudflare Speed endpoint</b><small>HTTPS · cache bypass · automatic edge routing</small></div>')}
function fix(){modal('🔧 Connection Advisor','<div class="result"><b>1. Move closer to Wi‑Fi</b><small>Reduce distance, walls and interference.</small></div><div class="result"><b>2. Pause heavy traffic</b><small>Stop downloads, cloud sync and game updates.</small></div><div class="result"><b>3. Restart equipment</b><small>Power-cycle the router/modem using its normal instructions.</small></div><div class="result"><b>4. Test again</b><small>Compare results from the same location at different times.</small></div>')}
function openLab(){$('lab').scrollIntoView({behavior:settingsData.motion==='reduce'?'auto':'smooth',block:'start'});toast('Diagnostics Lab opened')}
function bind(){
$('settings').onclick=settings;$('close').onclick=closeModal;$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});$('start').onclick=run;$('share').onclick=share;$('servers').onclick=servers;$('fix').onclick=fix;$('labbtn').onclick=openLab;
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x===b));const t={quick:'⚡ START QUICK TEST',gaming:'🎮 START GAMING TEST',streaming:'🎥 START STREAMING TEST',work:'💼 START WORK TEST',advanced:'🧪 START FULL DIAGNOSTICS'};$('start').textContent=t[mode]||t.quick});
window.addEventListener('resize',draw);window.addEventListener('online',()=>{$('online').textContent='● ONLINE'});window.addEventListener('offline',()=>{$('online').textContent='● OFFLINE'});const nc=navigator.connection;$('network').textContent=nc?.effectiveType?(nc.effectiveType.toUpperCase()+' / '+(navigator.onLine?'Online':'Offline')):(navigator.onLine?'Online':'Unknown');$('link').textContent=nc?.downlink?Number(nc.downlink).toFixed(1)+' Mbps':'Unavailable';$('save').textContent=nc?.saveData?'On':'Off';$('device').textContent=(navigator.userAgentData?.platform||navigator.platform||'Browser')+' · '+screen.width+'×'+screen.height;applyMotion();refreshUnits();renderHistory();draw();trace()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
